version: '3.8'

services:
  api:
    build: .
    ports:
      - "5001:5001"
    env_file: .env
    environment:
      - FLASK_APP=server.app
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=127.0.0.1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 
    volumes:
      - .:/app
      - sqlite_data:/app/data:rw
    working_dir: /app
    user: "root"  # Temporary for debugging
    command: flask --debug run

volumes:
  sqlite_data:
    driver: local
