version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - FLASK_APP=server.app
      - FLASK_RUN_PORT=8080
      - FLASK_RUN_HOST=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 
    volumes:
      - .:/app
      - sqlite_data:/app/data:rw
    working_dir: /app
    user: "root"  # Temporary for debugging
    command: waitress-serve --host=0.0.0.0 --port=8080 server.app:app

volumes:
  sqlite_data:
    driver: local
