version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - FLASK_APP=server.app
      - FLASK_RUN_PORT=8000
      - FLASK_RUN_HOST=127.0.0.1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 
    volumes:
      - .:/app
    working_dir: /app
    command: flask --debug run
