services:
  api:
    container_name: api
    build: .
    ports:
      - "5000:5000"  # Only expose to other containers, not to host
    env_file: .env
    environment:
      - FLASK_APP=server.app
      - FLASK_RUN_PORT=5000
      - FLASK_RUN_HOST=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    volumes:
      - .:/app
      - sqlite_data:/app/data:rw 
    working_dir: /app
    command: python api_test.py

volumes:
  sqlite_data:
    driver: local

networks:
  app_network:
    driver: bridge
